### PR TITLE
eng-5301-sats-connect-disable-automatic-detection-for-wbip-compatible-wallets

### PR DESCRIPTION
**Pull request by m-aboelenein**

### CODE REVIEW

**Review by victorkirov — APPROVED** [review]

**Comment by orenyomtov** [comment]
Hey, what's the reasoning for this change? I'm working on a WBIP004 compatible wallet and this breaks the dApps' automatic detection of it. @m-aboelenein @victorkirov

**Comment by aryzing** [comment]
Hi @orenyomtov, we disabled support at this time since we don't have the bandwidth to cater to all providers' particularities. The docs are being updated to reflect this. We may enable support for other providers again in the future

**Comment by aryzing** [comment]
@orenyomtov A bit more context: the WBIP004 standard doesn't seem to be actively maintained or agreed upon by all wallets in the space, which consumes a lot of resources when trying to make sats-connect work for all wallets. When the standard is more stable and better implemented by wallets in the space, we may enable support for it again.

If you absolutely need a connection kit that supports multiple wallets, you may want to check out [dynamic](https://www.dynamic.xyz/ecosystems/bitcoin)'s solution.

**Comment by orenyomtov** [comment]
Okay I see, thanks for the update

**Pull request merged**
